version: "3.9"

services:
  vllm-gemma3-27b-it:
    image: vllm/vllm-openai:latest
    container_name: vllm-gemma3-27b-it
    runtime: nvidia
    command: >
      --model google/gemma-3-12b-it
      --host 0.0.0.0
      --port 8000
      --max-model-len 4096
    ports:
      - "5095:8000"
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ipc: host
    deploy: {}
    restart: unless-stopped
